tools:
  - class_name: "verl.rstar.tools.sim_jupyter_tool.SimJupyterTool"
    config: 
      type: native
    tool_schema:
      type: "function"
      function:
        name: "jupyter_code"
        description: "Execute python code in a Jupyter notebook cell and return result"
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The python code to execute in a single cell"
          required: ["code"]
